import Head from "next/head";
import HeaderAuth from "../Components/HeaderAuth";
import React from "react";
import { Center, Container, Text } from "@mantine/core";

export default function Home() {
  return (
    <div>
      <HeaderAuth />
      <Head>
        <title>SIISO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center mt={200}>
        <Text size={30}>Добро пожаловать на официальный сайт С.И.И.С.О</Text>
      </Center>
      <Center>
        <Container>
          <Text size={20}>
            С.И.И.С.О - секретно-информационное инновационное сверх оружие.
            Основатель, генеральный директор, лучший сотрудник, а так же
            единственный сотрудник - Будеев Дмитрий Сергеевич
          </Text>
        </Container>
      </Center>
    </div>
  );
}
