import Head from "next/head";
import MainLayout from "../Components/MainLayout";
import { useRouter } from "next/router";
import HeaderAuth from "../Components/HeaderAuth";
import React from "react";

export default function Home() {
  return (
    <div>
      <HeaderAuth isAuth />
      <Head>
        <title>SIISO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
